spring:
  cloud:
    stream:
      bindings:
        orders_supplier-out-0:
          contentType: application/*+avro
          destination: orders
      schemaRegistryClient:
        endpoint: http://localhost:8081
#    schema:
#      avro:
#        schema-locations: classpath:avro/orders.avsc
#        subjectNamePrefix:  sensor-topic-value
#        subjectNamingStrategy: org.springframework.cloud.schema.registry.avro.SubjectPrefixOnlyNamingStrategy

server.port: 9009
