server.port: 8090

spring.cloud.stream:
  function:
    definition: process_inventory;process_orders;supplier;

spring.cloud.stream.bindings.process_inventory-in-0:
  destination: inventory
spring.cloud.stream.bindings.process_inventory-out-0:
  destination: inventory-out


spring.cloud.stream.bindings.process_orders-in-0:
  destination: orders
spring.cloud.stream.bindings.process_orders-out-0:
  destination: orders-out

spring.cloud.stream.bindings.supplier-out-0:
  destination: firstorder

spring.cloud.stream.kafka.streams.bindings.supplier-out-0:
  producer.keySerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
spring.cloud.stream.kafka.streams.bindings.supplier-in-0:
  producer.valueSerde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde


spring:
  cloud:
    stream:


spring.cloud.stream.kafka.streams.binder:
  brokers: localhost:9092
  configuration:
    schema.registry.url: http://localhost:8081
    commit.interval.ms: 1000


#spring.cloud.stream.kafka.streams.binder.configuration:
#  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#  default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde



spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde

